version: "2"
services:
  app:
    image: "node:8"
    container_name: app
    restart: always
    build: 
      context: .
    ports:
      - "3200:3200"
    volumes:
      - ./:/home/node/app
      - /home/node/app/node_modules
    links:
      - mongo
    depends_on:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"